### ISSUE TITLE
Removal Candidate

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/physfs#1]
This Package will be removed in 7 days from KCP.

Reason: **Broken**
`==> ERROR: A failure occurred in build().`
Reason: **Unmaintained**

Please see also: [Using KaOS Community Packages](https://kaosx.us/phpBB3/viewtopic.php?f=12&t=145) and [KCP Guide](https://kaosx.us/kcp-guide/)

**Comment by bvaudour** [comment]
If so, mark fifth too as removal candidate. I think other depends needed by fifth can be marked too.

**Comment by Adurol** [comment]
Thanks for pointing out. Looks like [fifth](https://github.com/KaOS-Community-Packages/fifth) is the main application. If nobody cares for phyfs in the remaining time, I will open an issue "removal candidate" for fifth, [webkitfltk](https://github.com/KaOS-Community-Packages/webkitfltk) and [liburlmatch](https://github.com/KaOS-Community-Packages/liburlmatch). I just hope I'm not overlooking a dependency with other packages...

**Comment by bvaudour** [comment]
I checked that, it seems not. To get all informations of all packages I did a (perfectible) script: https://gist.github.com/bvaudour/699e393ccea95c358bb17c9655685df6

With this script you should be able to check all depends (with Ctrl+F)

**Comment by Adurol** [comment]
Thanks for the script. Was thinking of doing something similar, but this works just fine for now (makedepends are missing, but kcp doesn't list them).

I `physfs` really gets removed, not only fifth but three games will break too: [manaplus](https://github.com/KaOS-Community-Packages/manaplus), [supertux2](https://github.com/KaOS-Community-Packages/supertux2) and [warzone2100](https://github.com/KaOS-Community-Packages/warzone2100). I'm not a gamer, so I have no problems with it. But it's also not clear how many are using these packages. If there are people who want to maintain it, I will be happy. If not, I must remove these four along with physfs.

**Comment by bvaudour** [comment]
Indeed. So, only liburlmatch and webkitfltk should be marked as removal candidates at this time IMO.

Thanks for your check. My script hadn't retrieved all KCP the first time I had launched it.

**Comment by Adurol** [comment]
So, after @bvaudour confirmed it, I can build it here again too. Reason unknown. I apologize for the fuss.
